/* ============================================
   AUTO-GENERATED — Do not edit manually!
   Generated by: node scripts/fetch-github.js
   Timestamp: 2026-03-03T04:25:17.244Z
   Total: 8 | Featured: 6 | Other: 2
   ============================================ */

const GITHUB_REPOS = [
  {
    "id": "voice-bot",
    "name": "Voice_Bot",
    "displayName": "PreciseCall Voice Bot",
    "description": "Voice bot deeloped for smothing the recruiting/hiring process.",
    "category": "nlp",
    "language": "JavaScript",
    "languageColor": "#f1e05a",
    "languageBreakdown": [
      {
        "name": "JavaScript",
        "percentage": 71,
        "color": "#f1e05a"
      },
      {
        "name": "CSS",
        "percentage": 26,
        "color": "#563d7c"
      },
      {
        "name": "Python",
        "percentage": 2,
        "color": "#3572A5"
      },
      {
        "name": "HTML",
        "percentage": 1,
        "color": "#e34c26"
      },
      {
        "name": "TypeScript",
        "percentage": 0,
        "color": "#3178c6"
      },
      {
        "name": "Dockerfile",
        "percentage": 0,
        "color": "#384d54"
      }
    ],
    "stars": 0,
    "forks": 0,
    "watchers": 0,
    "topics": [],
    "isPrivate": true,
    "isFork": false,
    "isArchived": false,
    "url": "https://github.com/Mr-K2901/Voice_Bot",
    "homepage": null,
    "defaultBranch": "develop",
    "size": 19176,
    "createdAt": "2025-08-08T16:55:17Z",
    "updatedAt": "2026-02-05T19:08:23Z",
    "pushedAt": "2026-02-05T19:08:08Z",
    "isFeatured": true,
    "tagline": "AI-Powered Conversational Recruiter",
    "accent": "#ff6b6b",
    "categoryLabel": "NLP / Voice AI",
    "fullDescription": "PreciseCall is a production-ready AI voice bot designed to streamline the recruiting and hiring process. It handles phone conversations using speech-to-text, natural language understanding, and text-to-speech to create a seamless conversational experience.\n\nThe system integrates with Twilio for telephony, uses a FastAPI backend for real-time processing, and features a React frontend dashboard for monitoring active calls and managing conversation flows. Built with WebSocket connections for low-latency real-time updates.",
    "features": [
      "Real-time speech-to-text transcription",
      "NLP-powered intent recognition & response generation",
      "Natural text-to-speech voice synthesis",
      "Twilio WhatsApp & voice call integration",
      "React dashboard for call monitoring",
      "WebSocket-based real-time updates",
      "Docker containerized deployment"
    ],
    "architecture": "Phone Call → Twilio → FastAPI WebSocket → STT → NLP Engine → Response Generator → TTS → Caller",
    "challenges": "Achieving low-latency responses in voice conversations — the bot needs to respond within 1-2 seconds to feel natural, requiring optimized NLP inference and audio streaming pipelines."
  },
  {
    "id": "facerecognitionx",
    "name": "FaceRecognitionX",
    "displayName": "FaceRecognitionX",
    "description": "No description available.",
    "category": "cv",
    "language": "Python",
    "languageColor": "#3572A5",
    "languageBreakdown": [
      {
        "name": "Python",
        "percentage": 100,
        "color": "#3572A5"
      }
    ],
    "stars": 0,
    "forks": 0,
    "watchers": 0,
    "topics": [],
    "isPrivate": false,
    "isFork": false,
    "isArchived": false,
    "url": "https://github.com/Mr-K2901/FaceRecognitionX",
    "homepage": null,
    "defaultBranch": "Kapil",
    "size": 151,
    "createdAt": "2026-01-31T18:44:07Z",
    "updatedAt": "2026-02-01T13:49:53Z",
    "pushedAt": "2026-02-01T13:49:49Z",
    "isFeatured": true,
    "tagline": "Real-Time Identity Verification System",
    "accent": "#ffd93d",
    "categoryLabel": "Computer Vision",
    "fullDescription": "A deep learning-based face recognition system using MTCNN for detection and InsightFace for high-accuracy identity matching. The pipeline handles the complete workflow: face detection → alignment → embedding generation → similarity matching against a known identity database.\n\nBuilt to work reliably across varying lighting conditions, angles, and partial occlusions. Features both real-time webcam recognition and batch processing modes.",
    "features": [
      "Multi-face detection with MTCNN",
      "ArcFace embedding generation via InsightFace",
      "Real-time webcam-based recognition",
      "Known/Unknown classification with configurable thresholds",
      "Batch processing for database enrollment",
      "Performance logging and accuracy metrics"
    ],
    "architecture": "Camera Feed → MTCNN Detector → Face Alignment → InsightFace Embeddings → Cosine Similarity → Identity Database → Result",
    "challenges": "Balancing false positive and false negative rates — choosing the right similarity threshold is critical and varies depending on the deployment environment and lighting conditions."
  },
  {
    "id": "tnp-portal",
    "name": "TnP_Portal",
    "displayName": "TnP Portal",
    "description": "No description available.",
    "category": "fullstack",
    "language": "Python",
    "languageColor": "#3572A5",
    "languageBreakdown": [
      {
        "name": "Python",
        "percentage": 100,
        "color": "#3572A5"
      },
      {
        "name": "JavaScript",
        "percentage": 0,
        "color": "#f1e05a"
      }
    ],
    "stars": 0,
    "forks": 0,
    "watchers": 0,
    "topics": [],
    "isPrivate": false,
    "isFork": false,
    "isArchived": false,
    "url": "https://github.com/Mr-K2901/TnP_Portal",
    "homepage": null,
    "defaultBranch": "main",
    "size": 11484,
    "createdAt": "2026-02-01T11:32:56Z",
    "updatedAt": "2026-02-01T12:00:18Z",
    "pushedAt": "2026-02-20T10:17:33Z",
    "isFeatured": true,
    "tagline": "Campus Recruitment Management Platform",
    "accent": "#a855f7",
    "categoryLabel": "Full Stack",
    "fullDescription": "A comprehensive campus recruitment management system built for Training & Placement cells. The portal digitizes the entire placement workflow — from student registration and resume management to company onboarding and interview scheduling.\n\nFeatures role-based access control (students, TPO admins, companies), database migrations with Alembic for reliable schema evolution, and a clean, responsive interface.",
    "features": [
      "Student profile & resume management",
      "Company registration and job posting",
      "Placement drive scheduling and management",
      "Role-based access control (Student/Admin/Company)",
      "Database migrations with Alembic",
      "RESTful API architecture"
    ],
    "architecture": "Frontend → FastAPI Backend → PostgreSQL (Alembic Migrations) → Docker",
    "challenges": "Designing a system flexible enough to handle different placement processes across departments while maintaining a consistent, intuitive user experience."
  },
  {
    "id": "iot-based-face-detection-and-recognition-using-esp-32",
    "name": "IOT-based-face-detection-and-recognition-using-ESP-32",
    "displayName": "IoT Vision System",
    "description": "A robust, low-latency wireless computer vision system using ESP32-CAM and Python OpenCV. Features fault-tolerant streaming, active frame dropping for real-time performance, and a data-fusion logging engine for industrial inspection scenarios",
    "category": "iot",
    "language": "Unknown",
    "languageColor": "#8b8b8b",
    "languageBreakdown": [],
    "stars": 0,
    "forks": 0,
    "watchers": 0,
    "topics": [],
    "isPrivate": true,
    "isFork": false,
    "isArchived": false,
    "url": "https://github.com/Mr-K2901/IOT-based-face-detection-and-recognition-using-ESP-32",
    "homepage": null,
    "defaultBranch": "main",
    "size": 1,
    "createdAt": "2025-12-26T11:50:45Z",
    "updatedAt": "2025-12-26T11:50:50Z",
    "pushedAt": "2025-12-27T05:08:47Z",
    "isFeatured": true,
    "tagline": "Edge AI for Industrial Inspection",
    "accent": "#4ecdc4",
    "categoryLabel": "IoT / Edge AI",
    "fullDescription": "A robust, fault-tolerant wireless computer vision system using ESP32-CAM and Python OpenCV. The system captures real-time video from ESP32-CAM modules, processes frames using a Producer-Consumer pattern, and performs face detection and recognition at the edge.\n\nDesigned for industrial inspection scenarios with features like active frame dropping for real-time performance, auto-reconnection on network failures, and a data-fusion logging engine for comprehensive audit trails.",
    "features": [
      "ESP32-CAM firmware with optimized streaming",
      "Fault-tolerant auto-reconnection mechanism",
      "Active frame dropping for real-time performance",
      "Producer-Consumer pattern for video processing",
      "Data-fusion logging engine for inspection records",
      "Streamlit dashboard for monitoring"
    ],
    "architecture": "ESP32-CAM → WiFi Stream → Python VideoStream (Producer) → Frame Queue → Detector (Consumer) → Logger → Dashboard",
    "challenges": "Maintaining stable, low-latency video streams over WiFi from ESP32-CAM modules while running real-time face recognition — all within the memory and bandwidth constraints of edge hardware."
  },
  {
    "id": "reviewemote-csv-sentiment-visualizer",
    "name": "ReviewEmote-CSV-Sentiment-Visualizer",
    "displayName": "ReviewEmote",
    "description": "ReviewEmote: Streamlit app for CSV sentiment analysis using DistilBERT. Features text chunking, 1-10 emoji ratings, progress tracking & Plotly charts. Zero-setup interface for non-technical users to analyze customer reviews at scale.",
    "category": "nlp",
    "language": "Unknown",
    "languageColor": "#8b8b8b",
    "languageBreakdown": [],
    "stars": 0,
    "forks": 0,
    "watchers": 0,
    "topics": [],
    "isPrivate": false,
    "isFork": false,
    "isArchived": false,
    "url": "https://github.com/Mr-K2901/ReviewEmote-CSV-Sentiment-Visualizer",
    "homepage": null,
    "defaultBranch": "main",
    "size": 0,
    "createdAt": "2025-05-24T04:14:58Z",
    "updatedAt": "2025-05-24T04:14:58Z",
    "pushedAt": "2025-05-24T04:14:58Z",
    "isFeatured": true,
    "tagline": "DistilBERT-Powered Sentiment Analyzer",
    "accent": "#00f0ff",
    "categoryLabel": "NLP / ML",
    "fullDescription": "ReviewEmote is a zero-setup Streamlit application that brings production-grade sentiment analysis to non-technical users. Upload a CSV of customer reviews, and the app automatically processes each entry through a DistilBERT transformer model.\n\nFeatures intelligent text chunking for long reviews, a 1-10 emoji rating system for intuitive visualization, real-time progress tracking, and interactive Plotly charts for exploring sentiment distributions and trends.",
    "features": [
      "DistilBERT transformer-based sentiment classification",
      "Smart text chunking for long-form reviews",
      "1-10 emoji rating scale visualization",
      "Real-time progress tracking with ETA",
      "Interactive Plotly charts and distributions",
      "Zero-setup CSV upload interface"
    ],
    "architecture": "CSV Upload → Text Chunking → DistilBERT Inference → Score Aggregation → Emoji Mapping → Plotly Visualization",
    "challenges": "Handling extremely long reviews that exceed the model's token limit — implemented intelligent text chunking that splits reviews into overlapping segments and aggregates predictions for accurate composite scores."
  },
  {
    "id": "blood-donation-camp",
    "name": "blood-donation-camp",
    "displayName": "Blood Donation Camp",
    "description": "No description available.",
    "category": "fullstack",
    "language": "HTML",
    "languageColor": "#e34c26",
    "languageBreakdown": [
      {
        "name": "HTML",
        "percentage": 77,
        "color": "#e34c26"
      },
      {
        "name": "JavaScript",
        "percentage": 23,
        "color": "#f1e05a"
      }
    ],
    "stars": 0,
    "forks": 0,
    "watchers": 0,
    "topics": [],
    "isPrivate": false,
    "isFork": false,
    "isArchived": false,
    "url": "https://github.com/Mr-K2901/blood-donation-camp",
    "homepage": null,
    "defaultBranch": "main",
    "size": 359,
    "createdAt": "2026-01-02T16:09:59Z",
    "updatedAt": "2026-01-04T12:11:09Z",
    "pushedAt": "2026-01-04T12:11:05Z",
    "isFeatured": true,
    "tagline": "Donor Registration & Management Portal",
    "accent": "#ec4899",
    "categoryLabel": "Web App",
    "fullDescription": "A web application designed for organizing and managing blood donation camp registrations. The system handles donor registration, blood type tracking, and camp event management with a clean, accessible interface.\n\nBuilt with vanilla HTML and JavaScript for maximum compatibility and easy deployment — can be hosted on GitHub Pages with zero configuration.",
    "features": [
      "Donor registration and data collection",
      "Blood type categorization and tracking",
      "Camp event scheduling and management",
      "Responsive design for mobile registration",
      "GitHub Pages deployment ready",
      "No server dependencies — fully client-side"
    ],
    "architecture": "HTML Frontend → JavaScript Logic → Local Storage / Static Hosting",
    "challenges": "Designing an intuitive registration flow that works smoothly on mobile devices at actual blood donation camps where network connectivity may be limited."
  },
  {
    "id": "ml",
    "name": "ML",
    "displayName": "ML Playground",
    "description": "Machine learning demos covering regression and classification algorithms with interactive Jupyter notebooks.",
    "category": "ml",
    "language": "Jupyter Notebook",
    "languageColor": "#DA5B0B",
    "languageBreakdown": [
      {
        "name": "Jupyter Notebook",
        "percentage": 100,
        "color": "#DA5B0B"
      }
    ],
    "stars": 0,
    "forks": 0,
    "watchers": 0,
    "topics": [],
    "isPrivate": false,
    "isFork": false,
    "isArchived": false,
    "url": "https://github.com/Mr-K2901/ML",
    "homepage": null,
    "defaultBranch": "main",
    "size": 2896,
    "createdAt": "2025-04-30T07:03:17Z",
    "updatedAt": "2026-01-21T08:38:39Z",
    "pushedAt": "2026-01-21T08:38:35Z",
    "isFeatured": false,
    "tagline": null,
    "accent": "#DA5B0B",
    "categoryLabel": "Machine Learning",
    "fullDescription": null,
    "features": [],
    "architecture": null,
    "challenges": null
  },
  {
    "id": "codsoft",
    "name": "Codsoft",
    "displayName": "CodSoft Internship",
    "description": "Python projects developed during CodSoft internship — covering core ML concepts and practical implementations.",
    "category": "ml",
    "language": "Python",
    "languageColor": "#3572A5",
    "languageBreakdown": [
      {
        "name": "Python",
        "percentage": 100,
        "color": "#3572A5"
      }
    ],
    "stars": 0,
    "forks": 0,
    "watchers": 0,
    "topics": [],
    "isPrivate": true,
    "isFork": false,
    "isArchived": false,
    "url": "https://github.com/Mr-K2901/Codsoft",
    "homepage": null,
    "defaultBranch": "main",
    "size": 45,
    "createdAt": "2024-02-15T12:03:34Z",
    "updatedAt": "2024-02-15T20:00:10Z",
    "pushedAt": "2024-02-15T20:10:45Z",
    "isFeatured": false,
    "tagline": null,
    "accent": "#3572A5",
    "categoryLabel": "Machine Learning",
    "fullDescription": null,
    "features": [],
    "architecture": null,
    "challenges": null
  }
];

const GITHUB_META = {
  username: "Mr-K2901",
  profileUrl: "https://github.com/Mr-K2901",
  avatarUrl: "https://avatars.githubusercontent.com/u/129107732?v=4",
  totalRepos: 8,
  publicRepos: 5,
  privateRepos: 3,
  featuredCount: 6,
  lastFetched: "2026-03-03T04:25:17.244Z"
};
